# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='versionNum',
            field=models.CharField(default=4.17, max_length=32),
            preserve_default=False,
        ),
    ]
